ARG BASE_IMAGE
ARG VERSION
FROM ${BASE_IMAGE}:${VERSION} AS source

USER root

# Install based on base dockerfile
# https://github.com/evmos/evmos/blob/main/Dockerfile

# Install minimum necessary dependencies for Starship
RUN apk add --no-cache curl make bash jq sed

WORKDIR /opt
