{{- range $chain := .Values.chains }}
{{- if not (hasPrefix "ethereum" $chain.name) }}
{{ $defaultFile := $.Files.Get "defaults.yaml" | fromYaml }}
{{ $chain := include "devnet.fullchain" (dict "name" $chain.id "file" $defaultFile "context" $) | fromJson }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: setup-scripts-{{ $chain.hostname }}
data:
  {{- range $k, $v := $chain.scripts }}
  {{- if hasKey $v "data" }}
  {{ $v.name }}: |-
    {{- $v.data | nindent 4 }}
  {{- else }}
  {{ $v.name }}: |-
    {{- $.Files.Get $v.file | nindent 4 }}
  {{- end }}
  {{- end }}
---
{{- if hasKey $chain "genesis" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: patch-{{ $chain.hostname }}
data:
  genesis.json: |-
    {{ toJson $chain.genesis | nindent 4 }}
---
{{- end }}
{{- if $chain.ics.enabled }}
{{ $icsChain := include "devnet.fullchain" (dict "name" $chain.ics.provider "file" $defaultFile "context" $) | fromJson }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-proposal-{{ $chain.hostname }}
data:
  proposal.json: |-
    {
      "title": "Add {{ $chain.name }} consumer chain",
      "summary": "Add {{ $chain.name }} consumer chain with id {{ $chain.id }}",
      "chain_id": "{{ $chain.id }}",
      "initial_height": {
        "revision_height": 1,
        "revision_number": 1
      },
      "genesis_hash": "d86d756e10118e66e6805e9cc476949da2e750098fcc7634fd0cc77f57a0b2b0",
      "binary_hash": "376cdbd3a222a3d5c730c9637454cd4dd925e2f9e2e0d0f3702fc922928583f1",
      "spawn_time": "2023-02-28T20:40:00.000000Z",
      "unbonding_period": 294000000000,
      "ccv_timeout_period": 259920000000,
      "transfer_timeout_period": 18000000000,
      "consumer_redistribution_fraction": "0.75",
      "blocks_per_distribution_transmission": 10,
      "historical_entries": 100,
      "distribution_transmission_channel": "",
      "top_N": 95,
      "validators_power_cap": 0,
      "validator_set_cap": 0,
      "allowlist": [],
      "denylist": [],
      "deposit": "10000{{ $icsChain.denom }}"
    }
---
{{- end }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keys
data:
  {{- range $path, $_ := .Files.Glob "configs/keys.json" }}
  {{ base $path }}: |-
    {{- $.Files.Get $path | nindent 4}}
  {{- end }}
---
# Configmap with setup-scripts that are not chain specific
apiVersion: v1
kind: ConfigMap
metadata:
  name: setup-scripts
data:
  transfer-tokens.sh: |-
    {{- $.Files.Get "scripts/default/transfer-tokens.sh" | nindent 4 }}
  ibc-connection.sh: |-
    {{- $.Files.Get "scripts/default/ibc-connection.sh" | nindent 4 }}
  create-ics.sh: |-
    {{- $.Files.Get "scripts/default/create-ics.sh" | nindent 4 }}
---
