{{ $portMap := dict "p2p" 26656 "address" 26658 "grpc" 9090 "grpc-web" 9091 "rest" 1317 }}
{{- range $chain := .Values.chains }}
{{- if not (hasPrefix "ethereum" $chain.name) }}
{{ $defaultFile := $.Files.Get "defaults.yaml" | fromYaml }}

{{ $chain := include "devnet.fullchain" (dict "name" $chain.id "file" $defaultFile "context" $) | fromJson }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $chain.hostname }}-genesis
  labels:
    app.kubernetes.io/name: {{ $chain.id }}-genesis
spec:
  clusterIP: None
  ports:
    {{- range $name, $port := $portMap }}
    - name: {{ $name }}
      port: {{ $port }}
      protocol: TCP
      targetPort: {{ $port }}
    {{- end }}
    - name: rpc
      port: 26657
      protocol: TCP
      targetPort: 26657
    {{- if $chain.metrics }}
    - name: metrics
      port: 26660
      protocol: TCP
      targetPort: 26660
    {{- end }}
    - name: exposer
      port: {{ $.Values.exposer.ports.rest | default 8081 }}
      protocol: TCP
      targetPort: {{ $.Values.exposer.ports.rest | default 8081 }}
    - name: faucet
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/name: {{ $chain.id }}-genesis
---
{{- if gt $chain.numValidators 1.0}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devnet.chain.name" $chain.id }}-validator
  labels:
    app.kubernetes.io/name: {{ $chain.id }}-validator
spec:
  clusterIP: None
  ports:
    {{- range $name, $port := $portMap }}
    - name: {{ $name }}
      port: {{ $port }}
      protocol: TCP
      targetPort: {{ $port }}
    {{- end }}
    - name: rpc
      port: 26657
      protocol: TCP
      targetPort: 26657
    {{- if $chain.metrics }}
    - name: metrics
      port: 26660
      protocol: TCP
      targetPort: 26660
    {{- end }}
    - name: exposer
      port: {{ $.Values.exposer.ports.rest | default 8081 }}
      protocol: TCP
      targetPort: {{ $.Values.exposer.ports.rest | default 8081 }}
  selector:
    app.kubernetes.io/name: {{ $chain.id }}-validator
---
{{- end }}
{{- end }}
{{- end }}