ARG BASE_IMAGE
ARG VERSION
FROM ${BASE_IMAGE}:${VERSION} AS source

FROM golang:1.21-bullseye

LABEL org.opencontainers.image.source="https://github.com/cosmology-tech/starship"

COPY --from=source /beacon-chain /usr/bin

RUN apt-get update && apt-get install -y \
    jq \
    curl \
    make \
    bash \
    jq \
    sed \
    build-essential \
    ca-certificates \
    libssl-dev \
    unzip \
    zip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt
