chains:
  - id: simapp
    name: simapp
    image: ghcr.io/hyperweb-io/starship/simapp:v0.47.3
    numValidators: 20
    ports:
      rest: 1317
      rpc: 26657
    faucet:
      image: ghcr.io/hyperweb-io/starship/cosmjs-faucet:v0.31.0-alpha.2

registry:
  enabled: true
  ports:
    rest: 8081

explorer:
  enabled: true
  ports:
    rest: 8080
