chains:
  - id: simapp
    name: simapp
    image: ghcr.io/hyperweb-io/starship/simapp:v0.47.3
    numValidators: 30
    ports:
      rest: 1317
      rpc: 26657
    faucet:
      # use v0.31.0-alpha.2 cosmjs-faucet for compatibility with simapp v0.47.3
      image: ghcr.io/hyperweb-io/starship/cosmjs-faucet:v0.31.0-alpha.2
      # provide more resources to faucet since the number of validators is higher
      # only a single faucet is spun up with the genesis node, so resources wont multiply
      # with the number of validators
      resources:
        cpu: "0.4"
        memory: "500M"

registry:
  enabled: true
  ports:
    rest: 8081

explorer:
  enabled: true
  ports:
    rest: 8080

exposer:
  resources:
    cpu: "0.1"
    memory: "100M"
