chains:
  - id: simapp
    name: custom
    image: ghcr.io/hyperweb-io/starship/simapp:v0.47.3
    numValidators: 2
    home: /root/.simapp
    binary: simd
    prefix: cosmos
    denom: stake
    coins: 100000000000000stake
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/cosmos/cosmos-sdk/tree/main/simapp
    ports:
      rest: 1317
      rpc: 26657
    faucet:
      image: ghcr.io/hyperweb-io/starship/cosmjs-faucet:v0.31.0-alpha.2
    resources:
      cpu: "1"
      memory: "2Gi"

registry:
  enabled: true
  ports:
    rest: 8081

explorer:
  enabled: true
  ports:
    rest: 8080
