// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: exposer/service.proto

package exposer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Exposer_GetNodeID_FullMethodName             = "/exposer.Exposer/GetNodeID"
	Exposer_GetPubKey_FullMethodName             = "/exposer.Exposer/GetPubKey"
	Exposer_GetGenesisFile_FullMethodName        = "/exposer.Exposer/GetGenesisFile"
	Exposer_GetKeys_FullMethodName               = "/exposer.Exposer/GetKeys"
	Exposer_GetPrivKey_FullMethodName            = "/exposer.Exposer/GetPrivKey"
	Exposer_GetPrivValidatorState_FullMethodName = "/exposer.Exposer/GetPrivValidatorState"
	Exposer_GetNodeKey_FullMethodName            = "/exposer.Exposer/GetNodeKey"
	Exposer_CreateChannel_FullMethodName         = "/exposer.Exposer/CreateChannel"
	Exposer_UpdateAllClients_FullMethodName      = "/exposer.Exposer/UpdateAllClients"
	Exposer_GetClients_FullMethodName            = "/exposer.Exposer/GetClients"
	Exposer_UpdateClients_FullMethodName         = "/exposer.Exposer/UpdateClients"
)

// ExposerClient is the client API for Exposer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Interface for service
type ExposerClient interface {
	// GetNodeID will returns current node id
	GetNodeID(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ResponseNodeID, error)
	// GetPubKey returns the public key of the current node
	GetPubKey(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ResponsePubKey, error)
	// GetGenesisFile returns the genesis file of the node
	GetGenesisFile(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*structpb.Struct, error)
	// GetKeysFile returns the keys of the node
	GetKeys(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Keys, error)
	// GetPrivKeys returns the keys of the node
	GetPrivKey(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PrivValidatorKey, error)
	// GetPrivState returns the keys of the node
	GetPrivValidatorState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PrivValidatorState, error)
	// GetNodeKey returns the keys of the node
	GetNodeKey(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodeKey, error)
	// Service functions for Relayer
	// CreateChannel creates channel between 2 given chains
	CreateChannel(ctx context.Context, in *RequestCreateChannel, opts ...grpc.CallOption) (*ResponseCreateChannel, error)
	// UpdateAllClients updates the clients of the chain
	UpdateAllClients(ctx context.Context, in *RequestUpdateAllClients, opts ...grpc.CallOption) (*ResponseUpdateAllClients, error)
	// GetClient updates the clients of the chain
	GetClients(ctx context.Context, in *RequestGetClients, opts ...grpc.CallOption) (*ResponseGetClients, error)
	// UpdateClient update the clients of the chain
	UpdateClients(ctx context.Context, in *RequestUpdateClients, opts ...grpc.CallOption) (*ResponseUpdateClients, error)
}

type exposerClient struct {
	cc grpc.ClientConnInterface
}

func NewExposerClient(cc grpc.ClientConnInterface) ExposerClient {
	return &exposerClient{cc}
}

func (c *exposerClient) GetNodeID(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ResponseNodeID, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseNodeID)
	err := c.cc.Invoke(ctx, Exposer_GetNodeID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exposerClient) GetPubKey(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ResponsePubKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponsePubKey)
	err := c.cc.Invoke(ctx, Exposer_GetPubKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exposerClient) GetGenesisFile(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*structpb.Struct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, Exposer_GetGenesisFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exposerClient) GetKeys(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Keys, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Keys)
	err := c.cc.Invoke(ctx, Exposer_GetKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exposerClient) GetPrivKey(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PrivValidatorKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrivValidatorKey)
	err := c.cc.Invoke(ctx, Exposer_GetPrivKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exposerClient) GetPrivValidatorState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PrivValidatorState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrivValidatorState)
	err := c.cc.Invoke(ctx, Exposer_GetPrivValidatorState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exposerClient) GetNodeKey(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodeKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeKey)
	err := c.cc.Invoke(ctx, Exposer_GetNodeKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exposerClient) CreateChannel(ctx context.Context, in *RequestCreateChannel, opts ...grpc.CallOption) (*ResponseCreateChannel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseCreateChannel)
	err := c.cc.Invoke(ctx, Exposer_CreateChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exposerClient) UpdateAllClients(ctx context.Context, in *RequestUpdateAllClients, opts ...grpc.CallOption) (*ResponseUpdateAllClients, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseUpdateAllClients)
	err := c.cc.Invoke(ctx, Exposer_UpdateAllClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exposerClient) GetClients(ctx context.Context, in *RequestGetClients, opts ...grpc.CallOption) (*ResponseGetClients, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseGetClients)
	err := c.cc.Invoke(ctx, Exposer_GetClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exposerClient) UpdateClients(ctx context.Context, in *RequestUpdateClients, opts ...grpc.CallOption) (*ResponseUpdateClients, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseUpdateClients)
	err := c.cc.Invoke(ctx, Exposer_UpdateClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExposerServer is the server API for Exposer service.
// All implementations must embed UnimplementedExposerServer
// for forward compatibility.
//
// Interface for service
type ExposerServer interface {
	// GetNodeID will returns current node id
	GetNodeID(context.Context, *emptypb.Empty) (*ResponseNodeID, error)
	// GetPubKey returns the public key of the current node
	GetPubKey(context.Context, *emptypb.Empty) (*ResponsePubKey, error)
	// GetGenesisFile returns the genesis file of the node
	GetGenesisFile(context.Context, *emptypb.Empty) (*structpb.Struct, error)
	// GetKeysFile returns the keys of the node
	GetKeys(context.Context, *emptypb.Empty) (*Keys, error)
	// GetPrivKeys returns the keys of the node
	GetPrivKey(context.Context, *emptypb.Empty) (*PrivValidatorKey, error)
	// GetPrivState returns the keys of the node
	GetPrivValidatorState(context.Context, *emptypb.Empty) (*PrivValidatorState, error)
	// GetNodeKey returns the keys of the node
	GetNodeKey(context.Context, *emptypb.Empty) (*NodeKey, error)
	// Service functions for Relayer
	// CreateChannel creates channel between 2 given chains
	CreateChannel(context.Context, *RequestCreateChannel) (*ResponseCreateChannel, error)
	// UpdateAllClients updates the clients of the chain
	UpdateAllClients(context.Context, *RequestUpdateAllClients) (*ResponseUpdateAllClients, error)
	// GetClient updates the clients of the chain
	GetClients(context.Context, *RequestGetClients) (*ResponseGetClients, error)
	// UpdateClient update the clients of the chain
	UpdateClients(context.Context, *RequestUpdateClients) (*ResponseUpdateClients, error)
	mustEmbedUnimplementedExposerServer()
}

// UnimplementedExposerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExposerServer struct{}

func (UnimplementedExposerServer) GetNodeID(context.Context, *emptypb.Empty) (*ResponseNodeID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeID not implemented")
}
func (UnimplementedExposerServer) GetPubKey(context.Context, *emptypb.Empty) (*ResponsePubKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPubKey not implemented")
}
func (UnimplementedExposerServer) GetGenesisFile(context.Context, *emptypb.Empty) (*structpb.Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGenesisFile not implemented")
}
func (UnimplementedExposerServer) GetKeys(context.Context, *emptypb.Empty) (*Keys, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeys not implemented")
}
func (UnimplementedExposerServer) GetPrivKey(context.Context, *emptypb.Empty) (*PrivValidatorKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrivKey not implemented")
}
func (UnimplementedExposerServer) GetPrivValidatorState(context.Context, *emptypb.Empty) (*PrivValidatorState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrivValidatorState not implemented")
}
func (UnimplementedExposerServer) GetNodeKey(context.Context, *emptypb.Empty) (*NodeKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeKey not implemented")
}
func (UnimplementedExposerServer) CreateChannel(context.Context, *RequestCreateChannel) (*ResponseCreateChannel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChannel not implemented")
}
func (UnimplementedExposerServer) UpdateAllClients(context.Context, *RequestUpdateAllClients) (*ResponseUpdateAllClients, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAllClients not implemented")
}
func (UnimplementedExposerServer) GetClients(context.Context, *RequestGetClients) (*ResponseGetClients, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClients not implemented")
}
func (UnimplementedExposerServer) UpdateClients(context.Context, *RequestUpdateClients) (*ResponseUpdateClients, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateClients not implemented")
}
func (UnimplementedExposerServer) mustEmbedUnimplementedExposerServer() {}
func (UnimplementedExposerServer) testEmbeddedByValue()                 {}

// UnsafeExposerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExposerServer will
// result in compilation errors.
type UnsafeExposerServer interface {
	mustEmbedUnimplementedExposerServer()
}

func RegisterExposerServer(s grpc.ServiceRegistrar, srv ExposerServer) {
	// If the following call pancis, it indicates UnimplementedExposerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Exposer_ServiceDesc, srv)
}

func _Exposer_GetNodeID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExposerServer).GetNodeID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exposer_GetNodeID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExposerServer).GetNodeID(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exposer_GetPubKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExposerServer).GetPubKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exposer_GetPubKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExposerServer).GetPubKey(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exposer_GetGenesisFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExposerServer).GetGenesisFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exposer_GetGenesisFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExposerServer).GetGenesisFile(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exposer_GetKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExposerServer).GetKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exposer_GetKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExposerServer).GetKeys(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exposer_GetPrivKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExposerServer).GetPrivKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exposer_GetPrivKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExposerServer).GetPrivKey(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exposer_GetPrivValidatorState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExposerServer).GetPrivValidatorState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exposer_GetPrivValidatorState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExposerServer).GetPrivValidatorState(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exposer_GetNodeKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExposerServer).GetNodeKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exposer_GetNodeKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExposerServer).GetNodeKey(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exposer_CreateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCreateChannel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExposerServer).CreateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exposer_CreateChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExposerServer).CreateChannel(ctx, req.(*RequestCreateChannel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exposer_UpdateAllClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestUpdateAllClients)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExposerServer).UpdateAllClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exposer_UpdateAllClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExposerServer).UpdateAllClients(ctx, req.(*RequestUpdateAllClients))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exposer_GetClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGetClients)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExposerServer).GetClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exposer_GetClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExposerServer).GetClients(ctx, req.(*RequestGetClients))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exposer_UpdateClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestUpdateClients)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExposerServer).UpdateClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exposer_UpdateClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExposerServer).UpdateClients(ctx, req.(*RequestUpdateClients))
	}
	return interceptor(ctx, in, info, handler)
}

// Exposer_ServiceDesc is the grpc.ServiceDesc for Exposer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Exposer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exposer.Exposer",
	HandlerType: (*ExposerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodeID",
			Handler:    _Exposer_GetNodeID_Handler,
		},
		{
			MethodName: "GetPubKey",
			Handler:    _Exposer_GetPubKey_Handler,
		},
		{
			MethodName: "GetGenesisFile",
			Handler:    _Exposer_GetGenesisFile_Handler,
		},
		{
			MethodName: "GetKeys",
			Handler:    _Exposer_GetKeys_Handler,
		},
		{
			MethodName: "GetPrivKey",
			Handler:    _Exposer_GetPrivKey_Handler,
		},
		{
			MethodName: "GetPrivValidatorState",
			Handler:    _Exposer_GetPrivValidatorState_Handler,
		},
		{
			MethodName: "GetNodeKey",
			Handler:    _Exposer_GetNodeKey_Handler,
		},
		{
			MethodName: "CreateChannel",
			Handler:    _Exposer_CreateChannel_Handler,
		},
		{
			MethodName: "UpdateAllClients",
			Handler:    _Exposer_UpdateAllClients_Handler,
		},
		{
			MethodName: "GetClients",
			Handler:    _Exposer_GetClients_Handler,
		},
		{
			MethodName: "UpdateClients",
			Handler:    _Exposer_UpdateClients_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exposer/service.proto",
}
